server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_assistant
    username: ai_user
    password: ai_user_pw123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  jwt:
    secret: this-is-a-very-very-very-long-jwt-secret-key-1234567890!!
    access-token-validity-ms: 3600000
